server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    addrs:
      - 127.0.0.1:6379
    db: 1
    password: your_password
    read_timeout: 0.2s
    write_timeout: 0.2s
